#!/bin/bash

if [ -z "$1" ]; then
    echo "Error: No input provided. Please enter a number."
    exit 1
fi

number=$1
factorial=1

for (( i=1; i<=number; i++ ))
do
    factorial=$((factorial * i))
done

echo "Factorial of $number is $factorial"
