#!/bin/bash

if [ -z "$1" ]; then
    echo "Error: No input provided. Please enter a number."
    exit 1
fi

number=$1
reverse=0

while [ $number -gt 0 ]; do
    remainder=$((number % 10))
    reverse=$((reverse * 10 + remainder))
    number=$((number / 10))
done

echo "Reversed number: $reverse"
