#!/bin/bash

if [ $# -ne 3 ]; then
    echo "Error: You must enter exactly three numbers."
    exit 1
fi

if [ $1 -eq $2 ] && [ $2 -eq $3 ]; then
    echo "The numbers are equal."
else
    echo "The numbers are not equal."
fi
